name: Crawl Startup Data

# do this as a cron job every 6h
# or trigger on push to master
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 */6 * * *"

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Crawl data
        run: |
          python3 scraper.py

      - name: Format data
        run: |
          python3 formatter.py

      - name: Create a new branch with only final.csv
        run: |
          git checkout -b data
          git add final.csv
          git commit -m "Update data"
          git push origin data
